### ISSUE TITLE
"psutil" module not available when triggering dispynode workers

### ISSUE THREAD

**Issue by Hecmay** [cornell-zhang/datuner#28] opened 2018-04-22 12:48 UTC
I was trying to run DATuner revamp with the `quartus` flow and get some errors.
```
[sx233@en-ec-zhang05 case]$ python ../src/datuner.py -f quartus -p 1 -b 8 -t 12s
[     0s]    INFO the current workdir is: /work/zhang-x1/users/sx233/software/datuner/case
[     0s]    INFO time limit: 12 seconds
  adding: design/ (stored 0%)
  adding: design/diffeq1.v (deflated 71%)
  adding: design/timing.sdc (deflated 5%)
  adding: quartus.py (deflated 57%)
  adding: run_quartus.tcl (deflated 50%)
  adding: setup.py (deflated 69%)
  adding: tune.py (deflated 62%)
2018-04-22 08:34:20 pycos - version 4.6.5 with epoll I/O notifier
2018-04-22 08:34:20 dispy - dispy client version: 4.8.5
2018-04-22 08:34:20 dispy - Storing fault recovery information in "_dispy_20180422083420"
dispynode.py                                                                                   100%   85KB  85.0KB/s   00:00

  "psutil" module is not available;
    node status (CPU, memory, disk and swap space usage) will not be sent to clients
2018-04-22 08:34:21 dispynode - dispynode version: 4.8.5, PID: 11163
2018-04-22 08:34:21 pycos - version 4.6.5 with epoll I/O notifier
```
DATuner just got stuck here with no more response. The error occurs when triggering dispynode worker using `python dispynode.py --serve 1 --clean --dest_path_prefix dispytmp` in `$DATUNER_HOME/src/datuner.py +322` :
```
  cluster = dispy.JobCluster(tune_function, depends = ['package.zip'])

  # copy files to and start up dispynode.py on worker machines
  # this can be removed from release code if we assume users manually start dispy
  for i in range(len(machines)):
    machine_addr = machines[i % len(machines)]

    subprocess.call(['scp', DATUNER_HOME + '/releases/Linux_x86_64/install/bin/dispynode.py', machine_addr + ':' +workspace]);
    subprocess.Popen(['ssh', machine_addr, 'cd ' + workspace + \
      '; python dispynode.py --serve 1 --clean --dest_path_prefix dispytmp_' + str(i)])
```
we should have checked whether the worker machine has installed the dependencies before running dispynode

**Comment by jg925** [comment] 2018-06-28 18:00
@Hecmay Modeling the other installations, I added the psutil installation to the opentuner Makefile. However, this causes it to not pass the CircleCi tests, saying that the root cause of the error is with the opentuner installation. I am not sure if this is due to the psutil installation being added to the incorrect Makefile and if there is a better place to install psutil.

**Comment by zhangzhiru** [comment] 2018-06-28 19:20
@Hecmay Shaojie, do you have time to work with Jinny to resolve this issue?

**Comment by eu49** [comment] 2018-07-01 17:22
I have first upgraded the Python version from 2.7.5 to 2.7.14 to prevent having outdated ssl module. Secondly, I disabled saving cache in the testing platform because the installation was being performed on the restored directory from the previous build. Later, we can consider having proper checksum covering all the Makefiles that are in different directories, so that CircleCI does not re-build from scratch each time new changes are committed. To sum up, DATuner build is successful (including psutil) and is verified by CircleCI.

**Closed by eu49** 2018-07-01 17:22 UTC
Labels: bug
